#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Jun 19 17:31:38 CST 2026
maven-metadata-central.xml.lastUpdated=1781348486505
maven-metadata-nexus.xml/@default-nexus-http\://nexus.ci.umpay.com.cn/nexus/content/groups/public/.lastUpdated=1781861498595
maven-metadata-nexus-aliyun.xml.lastUpdated=1781343364392
maven-metadata-nexus.xml.error=Could not transfer metadata org.springframework.boot\:spring-boot-maven-plugin/maven-metadata.xml from/to nexus (http\://nexus.ci.umpay.com.cn/nexus/content/groups/public/)\: Transfer failed for http\://nexus.ci.umpay.com.cn/nexus/content/groups/public/org/springframework/boot/spring-boot-maven-plugin/maven-metadata.xml 502 Bad Gateway
