server:
  port: 8085
spring:
  application:
    name: settle-module
  profiles:
    active: dev
reconcile:
  channel-code: DEFAULT
  parse-script-code: DEFAULT_CSV_PARSE
  compare-script-code: DEFAULT_ORDER_COMPARE
settle:
  reconcile:
    enabled: false
    required: false
xxl:
  job:
    enable: true
    addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    appname: ${spring.application.name}
    ip:
    port: 9990
    logretentiondays: 30
    logpath: /log