#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Fri Mar 06 13:59:45 CST 2026
maven-metadata-nexus-aliyun.xml.error=
maven-metadata-nexus-aliyun.xml.lastUpdated=1772776785721
